# `.nav.yml` is provided by https://lukasgeiter.github.io/mkdocs-awesome-nav
nav:
  - Questions & Help: help.md
  - Contributing: contributing.md
  - Development: development.md
  - Code of Conduct: code_of_conduct.md
  - Dev Guides: devguides
