repos:
- repo: local
  hooks:
    # See https://stackoverflow.com/questions/70778806
    - id: tox
      name: tox
      entry: .venv/bin/tox
      args: ["-e", "mypy,ruff"]
      language: system
      pass_filenames: false
