# `.nav.yml` is provided by https://lukasgeiter.github.io/mkdocs-awesome-nav
nav:
  - Rendering JS / CSS: rendering_js_css.md
  - HTML fragments: html_fragments.md
  - Prop drilling and provide / inject: provide_inject.md
  - Lifecycle hooks: hooks.md
  - Registering components: component_registry.md
  - Component caching: component_caching.md
  - Component context and scope: component_context_scope.md
  - Custom template tags: template_tags.md
  - Tag formatters: tag_formatters.md
  - Extensions: extensions.md
  - Testing: testing.md
  - Component libraries: component_libraries.md
