# `.nav.yml` is provided by https://lukasgeiter.github.io/mkdocs-awesome-nav
nav:
  - index.md
  - Scenarios:
    - HTML fragments: ./fragments
    - Error handling: ./error_fallback
    - Recursion: ./recursion
  - Components:
    - FormGrid: ./form_grid
    - Tabs (AlpineJS): ./tabs
