# `.nav.yml` is provided by https://lukasgeiter.github.io/mkdocs-awesome-nav
nav:
  - index.md
  - Components:
    - ErrorFallback: ./error_fallback
    - FormGrid: ./form_grid
    - Recursion: ./recursion
    - Tabs (AlpineJS): ./tabs
