# `.nav.yml` is provided by https://lukasgeiter.github.io/mkdocs-awesome-nav
nav:
  - index.md
  - Scenarios:
    - Form Submission: ./form_submission
    - HTML fragments: ./fragments
    - Error handling: ./error_fallback
    - Recursion: ./recursion
    - A/B testing: ./ab_testing
    - Analytics: ./analytics
  - Components:
    - FormGrid: ./form_grid
    - Tabs (AlpineJS): ./tabs
