# For navigation content inspo see Pydantic https://docs.pydantic.dev/latest
#
# `.nav.yml` is provided by https://lukasgeiter.github.io/mkdocs-awesome-nav
nav:
  - Home: README.md
  - overview
  - Getting Started: getting_started
  - "Documentation: Concepts": concepts
  - "Documentation: API Reference": reference
  - "Documentation: Guides": guides
  - "Documentation: Upgrading": upgrading
  - Migrating from safer_staticfiles: migrating_from_safer_staticfiles.md
  - plugins
  - examples
  - community
  - Release Notes: releases
