# `.nav.yml` is provided by https://lukasgeiter.github.io/mkdocs-awesome-nav
nav:
  - API: api.md
  - CLI commands: commands.md
  - Components: components.md
  - Exceptions: exceptions.md
  - Extension hooks: extension_hooks.md
  - Extension commands API: extension_commands.md
  - Extension URLs API: extension_urls.md
  - Settings: settings.md
  - Signals: signals.md
  - Tag formatters: tag_formatters.md
  - Template tags: template_tags.md
  - Template variables: template_vars.md
  - URLs: urls.md
  - Testing API: testing_api.md
