name: Notify Discord on new issues

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Discord (development channel)
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_DEVELOPMENT }}
        run: |
          payload=$(jq -n \
            --arg title "${{ github.event.issue.title }}" \
            --arg url "${{ github.event.issue.html_url }}" \
            --arg user "${{ github.event.issue.user.login }}" \
            --arg repo "${{ github.repository }}" \
            --arg number "#${{ github.event.issue.number }}" \
            '{
              "username": "GitHub Issues",
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "embeds": [
                {
                  "title": "New issue: \($number) \($title)",
                  "url": \($url),
                  "color": 3447003,
                  "author": {"name": \($user)},
                  "footer": {"text": \($repo)},
                  "timestamp": "${{ github.event.issue.created_at }}"
                }
              ]
            }')
          curl -sS -X POST -H "Content-Type: application/json" -d "$payload" "$DISCORD_WEBHOOK_URL" | cat
